---
# tasks file for poet

  - name: yum install 
    yum: name={{ item }} state=present
    with_items:
      - gcc 

  - name: get cpanm
    get_url: 
      url=http://cpanmin.us
      dest=/usr/local/bin/cpanm
      mode=0755

  - name: install Poet+mason
    command: /usr/local/bin/cpanm -S --notest Poet

